services:
  giftmash:
    build: .
    container_name: giftmash
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./db:/app/db
    environment:
      RAILS_ENV: development
    command: ["bin/rails", "server", "-b", "0.0.0.0"]