services:
  giftmash:
    build: .
    container_name: giftmash
    ports:
      - "3000:3000"
    volumes:
      - .:/giftmash
      - ./db:/giftmash/db 
    environment:
      RAILS_ENV: development
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

  giftmash_test:
    build: .
    container_name: giftmash_test
    environment:
      RAILS_ENV: test
    volumes:
      - .:/giftmash
      - ./db:/giftmash/db
